In [1]:
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup as bs
import pandas as pd
import time

In [2]:
dfs = []

In [3]:
driver = webdriver.Chrome()
url = 'https://www.bseindia.com/markets/keystatics/Keystat_index.aspx'
driver.get(url)

In [4]:
Click_buttons = []
for x in range(0,6):
    link = f'//*[@id="ContentPlaceHolder1_gvReport_Linkbtn_{x}"]'
    Click_buttons.append(link)

In [5]:
for link in Click_buttons:
    try:
        # Wait for the element to be clickable
        element = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, f'{link}'))
        )

        # Scroll the element into view
        driver.execute_script("arguments[0].scrollIntoView();", element)

        # Click the element
        element.click()
        time.sleep(5)  # Give some time for the page to load

        # Continue with your scraping logic
        page_source = driver.page_source
        soup = bs(page_source, 'html.parser')
        table = soup.find('table', id='ContentPlaceHolder1_gvYearwise')
        rows = table.find_all('tr')
        headers = [th.text.strip() for th in rows[0].find_all('th')]
        data = []
        for row in rows[1:]:
            row_data = [td.text.strip() for td in row.find_all('td')]
            data.append(row_data)
        temp_df = pd.DataFrame(data, columns=headers)
        dfs.append(temp_df)

        # Scroll to the top of the page
        driver.execute_script("window.scrollTo(0, 0);")

    except Exception as e:
        print(f"Error processing element {i}: {e}")

# Concatenate all DataFrames into a single DataFrame
final_df = pd.concat(dfs, ignore_index=True)

# Close the WebDriver
driver.quit()

In [6]:
final_df.head(50)

      Year       High        Low      Close PE Ratios PB Ratios Dividend Yield
0   Jan-24  73,427.59  70,001.60  70,700.67     25.22      3.68           1.11
1   Dec-23  72,484.34  67,149.07  72,240.26     24.93      3.63           1.13
2   Nov-23  67,069.89  63,550.46  66,988.44     23.11      3.37           1.23
3   Oct-23  66,592.16  63,092.98  63,874.93     23.56      3.46           1.25
4   Sep-23  67,927.23  64,818.37  65,828.41     24.26      3.60           1.23
5   Aug-23  66,658.12  64,723.63  64,831.41     23.93      3.54           1.23
6   Jul-23  67,619.17  64,836.16  66,527.67     24.93      3.57           1.23
7   Jun-23  64,768.58  62,359.14  64,718.56     23.33      3.32           1.31
8   May-23  63,036.12  61,002.17  62,622.24     23.48      3.28           1.29
9   Apr-23  61,209.46  58,793.08  61,112.44     22.60      3.28           1.23
10  Mar-23  60,498.48  57,084.91  58,991.52     22.21      3.23           1.24
11  Feb-23  61,682.25  58,795.97  58,962.12     22.84      3.34           1.20
12  Jan-23  61,343.96  58,699.20  59,549.90     23.28      3.37           1.18
13  Dec-22  63,583.07  59,754.10  60,840.74     23.62      3.44           1.16
14  Nov-22  63,303.01  60,425.47  63,099.65     23.34      3.43           1.16
15  Oct-22  60,786.70  56,683.40  60,746.59     22.44      3.33           1.22
16  Sep-22  60,676.12  56,147.23  57,426.92     22.76      3.36           1.22
17  Aug-22  60,411.20  57,367.47  59,537.07     22.89      3.38           1.22
18  Jul-22  57,619.27  52,094.25  57,570.25     22.04      3.16           1.29
19  Jun-22  56,432.65  50,921.22  53,018.94     21.79      3.10           1.29
20  May-22  57,184.21  52,632.48  55,566.41     22.45      3.18           1.18
21  Apr-22  60,845.10  56,009.07  57,060.87     25.40      3.54           0.98
22  Mar-22  58,890.92  52,260.82  58,568.51     24.82      3.44           0.99
23  Feb-22  59,618.51  54,383.20  56,247.28     25.75      3.53           0.96
24  Jan-22  61,475.15  56,409.63  58,014.17     28.17      3.68           0.91
25  Dec-21  59,203.37  55,132.68  58,253.82     27.17      3.54           0.96
26  Nov-21  61,036.56  56,382.93  57,064.87     28.56      3.66           0.95
27  Oct-21  62,245.43  58,551.14  59,306.93     31.08      3.83           0.90
28  Sep-21  60,412.32  57,263.90  59,126.36     30.62      3.75           0.92
29  Aug-21  57,625.26  52,804.08  57,552.39     30.00      3.53           0.98
30  Jul-21  53,290.81  51,802.73  52,586.84     31.59      3.39           1.03
31  Jun-21  53,126.73  51,450.58  52,482.71     32.15      3.34           0.97
32  May-21  52,013.22  48,028.07  51,937.44     31.35      3.19           0.86
33  Apr-21  50,375.77  47,204.50  48,782.36     33.50      3.28           0.77
34  Mar-21  51,821.84  48,236.35  49,509.15     34.94      3.38           0.72
35  Feb-21  52,516.76  46,433.65  49,099.99     35.13      3.43           0.75
36  Jan-21  50,184.01  46,160.46  46,285.77     33.68      3.31           0.82
37  Dec-20  47,896.97  44,118.10  47,751.33     32.77      3.11           0.87
38  Nov-20  44,825.37  39,334.92  44,149.72     30.45      2.87           0.94
39  Oct-20  41,048.05  38,410.20  39,614.07     29.10      2.97           0.99
40  Sep-20  39,359.51  36,495.98  38,067.93     28.09      2.89           1.01
41  Aug-20  40,010.17  36,911.23  38,628.29     27.28      2.88           1.00
42  Jul-20  38,617.03  34,927.20  37,606.89     24.67      2.77           1.04
43  Jun-20  35,706.55  32,348.10  34,915.80     21.82      2.58           1.09
44  May-20  32,845.48  29,968.45  32,424.10     19.46      2.36           1.21
45  Apr-20  33,887.25  27,500.79  33,717.62     18.78      2.39           1.34
46  Mar-20  39,083.17  25,638.90  29,468.49     19.55      2.49           1.39
47  Feb-20  41,709.30  38,219.97  38,297.29     24.64      3.16           1.05
48  Jan-20  42,273.87  40,476.55  40,723.49     25.67      3.21           1.03
49  Dec-19  41,809.96  40,135.37  41,253.74     27.95      3.04           1.10

In [7]:
#final_df.to_csv("Sensex_51,Years.csv")